FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8081

CMD ["celery", "-A", "app.celery_worker.celery_app", "worker", "--loglevel=info"]
